export const UI_TOKEN_NAMES = [
  '--ui-color-primary',
  '--ui-color-on-primary',
  '--ui-color-text',
  '--ui-color-surface',
  '--ui-color-surface-muted',
  '--ui-color-border',
  '--ui-color-focus',
  '--ui-radius-sm',
  '--ui-radius-md',
  '--ui-radius-lg',
  '--ui-space-1',
  '--ui-space-2',
  '--ui-space-4',
  '--ui-space-6',
  '--ui-space-8',
  '--ui-font-family-sans',
  '--ui-font-size-sm',
  '--ui-font-size-md',
  '--ui-font-size-lg',
  '--ui-font-size-xl',
  '--ui-font-weight-regular',
  '--ui-font-weight-semibold',
  '--ui-line-height-normal',
  '--ui-line-height-tight',
  '--ui-shadow-md',
] as const;
